export enum LoaiThietLapMacDinh {
    Logo,
    KieuChu,
    CoChu,
    MauChu,
    HienThiQRCode,
    LapLaiThongTinKhiHoaDonCoNhieuTrang,
    ThietLapDongKyHieuCot,
    SoDongTrang,
    HinhNenMacDinh,
    HinhNenTaiLen,
    KhungVienMacDinh
}

export enum LoaiTuyChinhChiTiet {
    ThongTinNguoiBan = 1,
    ThongTinHoaDon = 2,
    MauSoKyHieuSoHoaDon = 3,
    ThongTinNguoiMua = 4,
    MaQRCode = 5,
    ThongTinVeHangHoaDichVu = 6,
    ThongTinVeTongGiaTriHHDV = 7,
    ThongTinNgoaiTe = 8,
    ThongTinNguoiKy = 9,
    ThongTinTraCuu = 10,
    ThongTinMaCuaCoQuanThue = 11
}

export enum LoaiChiTietTuyChonNoiDung {
    CustomThongTinHoaDon = -2,
    CustomNguoiBan = -1,
    ///////////////////////////////
    None,
    TenDonViNguoiBan,
    MaSoThueNguoiBan,
    DiaChiNguoiBan,
    DienThoaiNguoiBan,
    FaxNguoiBan,
    WebsiteNguoiBan,
    EmailNguoiBan,
    SoTaiKhoanNguoiBan,
    /////////////////////////
    TenLoaiHoaDon,
    TenKhacLoaiHoaDon,
    TenMauHoaDon,
    NgayThangNamTieuDe,
    ////////////////////////
    MauSo,
    KyHieu,
    SoHoaDon,
    ////////////////////////,
    HoTenNguoiMua,
    TenDonViNguoiMua,
    MaSoThueNguoiMua,
    DiaChiNguoiMua,
    HinhThucThanhToan,
    SoTaiKhoanNguoiMua,
    ThoiHanThanhToan,
    DiaChiGiaoHang,
    ////////////////////////,
    STT,
    MaHang,
    TenHangHoaDichVu,
    QuyCach,
    DonViTinh,
    SoLuong,
    DonGia,
    ThanhTien,
    GhiChuHHDV,
    ////////////////////////
    TyLeChietKhau,
    SoTienChietKhau,
    CongTienHang,
    ThueSuatGTGT,
    TienThueGTGT,
    TongTienThanhToan,
    SoTienBangChu,
    GhiChuTongTien,
    ///////////////////////
    TyGia,
    QuyDoi,
    ///////////////////////
    TieuDeKyNguoiChuyenDoi,
    KyGhiRoHoTenNguoiChuyenDoi,
    TieuDeKyNguoiMua,
    KyGhiRoHoTenNguoiMua,
    TieuDeKyNguoiBan,
    KyGhiRoHoTenNguoiBan,
    ///////////////////////
    TraCuuTai,
    CanKiemTraDoiChieu,
    PhatHanhBoi,
    LinkTraCuu,
    MaTraCuu,
    ///////////////////////
    GhiChuBenMua,
    ///////////////////////
    MaCuaCQT,
    ////////////////////////
    TruongThongTinBoSung1,
    TruongThongTinBoSung2,
    TruongThongTinBoSung3,
    TruongThongTinBoSung4,
    TruongThongTinBoSung5,
    TruongThongTinBoSung6,
    TruongThongTinBoSung7,
    TruongThongTinBoSung8,
    TruongThongTinBoSung9,
    TruongThongTinBoSung10,
    ///////////////////////
    TruongMoRongChiTiet1,
    TruongMoRongChiTiet2,
    TruongMoRongChiTiet3,
    TruongMoRongChiTiet4,
    TruongMoRongChiTiet5,
    TruongMoRongChiTiet6,
    TruongMoRongChiTiet7,
    TruongMoRongChiTiet8,
    TruongMoRongChiTiet9,
    TruongMoRongChiTiet10,
    ///////////////////////
    KhuVucPhiThueQuan,
    CongTienHangDaTruCK,
    //////////////////////
    TongHopThueGTGT,
    TongTienKhongKeKhaiThue,
    TongTienKhongChiuThueGTGT,
    TongTienChiuThueSuat0,
    TongTienChiuThueSuat5,
    TongTienChiuThueSuat10,
    TongTienChiuThueSuatKhac,
    TongCongTongHopThueGTGT,
    ///////////////////////
    TyLeChietKhauHHDV,
    TienChietKhauHHDV,
    ThanhTienDaTruCKHHDV,
    ThueSuatHHDV,
    TienThueHHDV,
    ThanhTienSauThueHHDV,
    DongTienThanhToan,
    TyGiaHHDV,
    ///////////////////////
    TongTienChiuThueSuat8,
    ///////////////////////
    CanCuSo,
    Cua,
    DiaChiKhoNhanHang,
    DiaChiKhoXuatHang,
    VeViecDienGiai,
    HoTenNguoiNhanHang,
    HoTenNguoiXuatHang,
    HopDongVanChuyenSo,
    NgayCanCu,
    PhuongThucVanChuyen,
    TenNguoiVanChuyen,
    SoLuongNhapXuat,
    SoLuongNhap,
    TieuDeKyNguoiLapPhieu,
    KyGhiRoHoTenNguoiLapPhieu,
    TieuDeKyNguoiNhanHang,
    KyGhiRoHoTenNguoiNhanHang,
    TieuDeKyThuKhoXuat,
    KyGhiRoHoTenThuKhoXuat,
    TieuDeKyNguoiVanChuyen,
    KyGhiRoHoTenNguoiVanChuyen,
    TieuDeKyThuKhoNhap,
    KyGhiRoHoTenThuKhoNhap,
    TieuDeKyThuTruongDonVi,
    KyGhiRoHoTenThuTruongDonVi,
    SoDienThoaiNguoiMua,
    CanCuocCongDanNguoiMua,
    TenNganHangNguoiBan,
    ////// Vé điện tử
    GiaVe,
    TenDichVu,
    TongTienThanhToanBangChu,
    DaBaoGom,
    GhiChuChanTrang,
    MaSoBiMat,
    NguoiLap,
    QRCode,
    NoiDungMaTraCuu,
    NoiDungQrCode,
    KyHieuKH,
    TenPhuongTien,
}